

	/*
	using ArrayArrayT = ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>;
	std::string type_name = "";
	py::class_<ArrayArrayT>(m, ("ArrayArray" + type_name).c_str())
		.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
		.def("append", &ArrayArrayT::append, py::arg("ary"))
		.def("removeAt", &ArrayArrayT::removeAt, py::arg("idx"))
		.def("__len__", &ArrayArrayT::size)
		.def("__getitem__", &ArrayArrayT::getItem, py::arg("idx"))
		.def("to_array", &ArrayArrayT::to_array)
		.def_readwrite("keys", &ArrayArrayT::keys)
		.def_readwrite("values", &ArrayArrayT::values);
	*/

/*
for (auto [k, v]: {
	std::pair<size_t, size_t>{DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN}, 
	std::pair<size_t, size_t>{2048, 2048}, 
	std::pair<size_t, size_t>{COMBINATIONS_KEYS_LEN, COMBINATIONS_VALUES_LEN}, 
	std::pair<size_t, size_t>{32, 32}
	}) {
	py::class_<ArrayArray<int64_t, k, v>, std::shared_ptr<ArrayArray<int64_t, k, v>>>(m, "ArrayArray65536")
	.def(py::init())
	.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
	.def("append_small_vector32", &ArrayArray<int64_t, k, v>::append_small_vector<32>)
	.def("push_back_small_vector32", &ArrayArray<int64_t, k, v>::push_back_small_vector<32>)
	.def("append_small_vector24", &ArrayArray<int64_t, k, v>::append_small_vector<24>)
	.def("push_back_small_vector24", &ArrayArray<int64_t, k, v>::push_back_small_vector<24>)
	.def("append32", &ArrayArray<int64_t, k, v>::append<boost::container::small_vector<int64_t, 32>>)
	.def("push_back32", &ArrayArray<int64_t, k, v>::push_back<boost::container::small_vector<int64_t, 32>>)
	.def("append24", &ArrayArray<int64_t, k, v>::append<boost::container::small_vector<int64_t, 24>>)
	.def("push_back24", &ArrayArray<int64_t, k, v>::push_back<boost::container::small_vector<int64_t, 24>>)
	.def("append01", &ArrayArray<int64_t, k, v>::append<boost::container::small_vector<int64_t, 1>>)
	.def("push_back01", &ArrayArray<int64_t, k, v>::push_back<boost::container::small_vector<int64_t, 1>>)
	.def("append_vector", &ArrayArray<int64_t, k, v>::append<std::vector<int64_t>>)
	.def("push_back_vector", &ArrayArray<int64_t, k, v>::push_back<std::vector<int64_t>>)
	//.def("append32", &ArrayArray<int64_t, k, v>::append<32>)
	//.def("push_back32", &ArrayArray<int64_t, k, v>::push_back<32>)
	//.def("append24", &ArrayArray<int64_t, k, v>::append<24>)
	//.def("push_back24", &ArrayArray<int64_t, k, v>::push_back<24>)
	//.def("append1", &ArrayArray<int64_t, k, v>::append<1>)
	//.def("push_back1", &ArrayArray<int64_t, k, v>::push_back<1>)
	.def("removeAt", &ArrayArray<int64_t, k, v>::removeAt)
	.def("remove_at", &ArrayArray<int64_t, k, v>::remove_at)
	.def("to_array", &ArrayArray<int64_t, k, v>::to_array)
	.def("to_list", &ArrayArray<int64_t, k, v>::to_list)
	.def("keys_len", &ArrayArray<int64_t, k, v>::keys_len)
	.def("keys_size", &ArrayArray<int64_t, k, v>::keys_size)
	.def("values_len", &ArrayArray<int64_t, k, v>::values_len)
	.def("values_size", &ArrayArray<int64_t, k, v>::values_size)
	//.def("get_size", &ArrayArray<int64_t, k, v>::size)
	//.def("get_item", &ArrayArray<int64_t, k, v>::getItem)
	.def("__len__", &ArrayArray<int64_t, k, v>::size)
	//.def("__getitem__", &ArrayArray<int64_t, k, v>::get<std::vector<int64_t>>);
	.def("__getitem__", &ArrayArray<int64_t, k, v>::get<boost::container::small_vector<int64_t, 24>>);
}
*/

py::class_<ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>, std::shared_ptr<ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>>>(m, "ArrayArray65536")
.def(py::init())
.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
.def("append_small_vector32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append_small_vector<32>)
.def("push_back_small_vector32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back_small_vector<32>)
.def("append_small_vector24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append_small_vector<24>)
.def("push_back_small_vector24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back_small_vector<24>)
.def("append32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<boost::container::small_vector<int64_t, 32>>)
.def("push_back32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<boost::container::small_vector<int64_t, 32>>)
.def("append24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<boost::container::small_vector<int64_t, 24>>)
.def("push_back24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<boost::container::small_vector<int64_t, 24>>)
.def("append01", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<boost::container::small_vector<int64_t, 1>>)
.def("push_back01", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<boost::container::small_vector<int64_t, 1>>)
.def("append_vector", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<std::vector<int64_t>>)
.def("push_back_vector", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<std::vector<int64_t>>)
//.def("append32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<32>)
//.def("push_back32", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<32>)
//.def("append24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<24>)
//.def("push_back24", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<24>)
//.def("append1", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::append<1>)
//.def("push_back1", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::push_back<1>)
.def("removeAt", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::removeAt)
.def("remove_at", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::remove_at)
.def("to_array", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::to_array)
.def("to_list", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::to_list)
.def("keys_len", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::keys_len)
.def("keys_size", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::keys_size)
.def("values_len", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::values_len)
.def("values_size", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::values_size)
//.def("get_size", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::size)
//.def("get_item", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::getItem)
.def("__len__", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::size)
//.def("__getitem__", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::get<std::vector<int64_t>>);
.def("__getitem__", &ArrayArray<int64_t, DIVISORS_CACHE_KEYS_LEN, DIVISORS_CACHE_VALUES_LEN>::get<boost::container::small_vector<int64_t, 24>>);

py::class_<ArrayArray<int64_t, 2048, 2048>, std::shared_ptr<ArrayArray<int64_t, 2048, 2048>>>(m, "ArrayArray2048")
.def(py::init())
.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
//.def("append", &ArrayArray<int64_t, 2048, 2048>::append<24>)
//.def("push_back", &ArrayArray<int64_t, 2048, 2048>::push_back<24>)
.def("append32", &ArrayArray<int64_t, 2048, 2048>::append<boost::container::small_vector<int64_t, 32>>)
.def("push_back32", &ArrayArray<int64_t, 2048, 2048>::push_back<boost::container::small_vector<int64_t, 32>>)
.def("append24", &ArrayArray<int64_t, 2048, 2048>::append<boost::container::small_vector<int64_t, 24>>)
.def("push_back24", &ArrayArray<int64_t, 2048, 2048>::push_back<boost::container::small_vector<int64_t, 24>>)
.def("append_vector", &ArrayArray<int64_t, 2048, 2048>::append<std::vector<int64_t>>)
.def("push_back_vector", &ArrayArray<int64_t, 2048, 2048>::push_back<std::vector<int64_t>>)
.def("removeAt", &ArrayArray<int64_t, 2048, 2048>::removeAt)
.def("remove_at", &ArrayArray<int64_t, 2048, 2048>::remove_at)
.def("to_array", &ArrayArray<int64_t, 2048, 2048>::to_array)
.def("to_list", &ArrayArray<int64_t, 2048, 2048>::to_list)
.def("keys_len", &ArrayArray<int64_t, 2048, 2048>::keys_len)
.def("keys_size", &ArrayArray<int64_t, 2048, 2048>::keys_size)
.def("values_len", &ArrayArray<int64_t, 2048, 2048>::values_len)
.def("values_size", &ArrayArray<int64_t, 2048, 2048>::values_size)
//.def("get_size", &ArrayArray<int64_t, 2048, 2048>::size)
//.def("get_item", &ArrayArray<int64_t, 2048, 2048>::getItem)
.def("__len__", &ArrayArray<int64_t, 2048, 2048>::size)
.def("__getitem__", &ArrayArray<int64_t, 2048, 2048>::get<std::vector<int64_t>>);


py::class_<ArrayArray<int64_t, 724, 1218>, std::shared_ptr<ArrayArray<int64_t, 724, 1218>>>(m, "ArrayArray708")
.def(py::init())
.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
//.def("append", &ArrayArray<int64_t, 724, 1218>::append<32>)
//.def("push_back", &ArrayArray<int64_t, 724, 1218>::push_back<32>)
.def("append32", &ArrayArray<int64_t, 724, 1218>::append<boost::container::small_vector<int64_t, 32>>)
.def("push_back32", &ArrayArray<int64_t, 724, 1218>::push_back<boost::container::small_vector<int64_t, 32>>)
.def("append24", &ArrayArray<int64_t, 724, 1218>::append<boost::container::small_vector<int64_t, 24>>)
.def("push_back24", &ArrayArray<int64_t, 724, 1218>::push_back<boost::container::small_vector<int64_t, 24>>)
.def("append_vector", &ArrayArray<int64_t, 724, 1218>::append<std::vector<int64_t>>)
.def("push_back_vector", &ArrayArray<int64_t, 724, 1218>::push_back<std::vector<int64_t>>)
.def("push_back_small_vector", &ArrayArray<int64_t, 724, 1218>::push_back_small_vector<32>)
.def("removeAt", &ArrayArray<int64_t, 724, 1218>::removeAt)
.def("remove_at", &ArrayArray<int64_t, 724, 1218>::remove_at)
.def("to_array", &ArrayArray<int64_t, 724, 1218>::to_array)
.def("to_list", &ArrayArray<int64_t, 724, 1218>::to_list)
.def("keys_len", &ArrayArray<int64_t, 724, 1218>::keys_len)
.def("keys_size", &ArrayArray<int64_t, 724, 1218>::keys_size)
.def("keys_capacity", &ArrayArray<int64_t, 724, 1218>::keys_capacity)
.def("values_len", &ArrayArray<int64_t, 724, 1218>::values_len)
.def("values_size", &ArrayArray<int64_t, 724, 1218>::values_size)
.def("values_capacity", &ArrayArray<int64_t, 724, 1218>::values_capacity)
//.def("get_size", &ArrayArray<int64_t, 724, 1218>::size)
//.def("get_item", &ArrayArray<int64_t, 724, 1218>::getItem)
.def("__len__", &ArrayArray<int64_t, 724, 1218>::size)
.def("__getitem__", &ArrayArray<int64_t, 724, 1218>::get<std::vector<int64_t>>);


py::class_<ArrayArray<int64_t, 32, 32>, std::shared_ptr<ArrayArray<int64_t, 32, 32>>>(m, "ArrayArray32")
.def(py::init())
.def(py::init<size_t, bool>(), py::arg("capacity"), py::arg("resizeable"))
//.def("append", &ArrayArray<int64_t, 32, 32>::append<24>)
//.def("push_back", &ArrayArray<int64_t, 32, 32>::push_back<24>)
.def("append32", &ArrayArray<int64_t, 32, 32>::append<boost::container::small_vector<int64_t, 32>>)
.def("push_back32", &ArrayArray<int64_t, 32, 32>::push_back<boost::container::small_vector<int64_t, 32>>)
.def("append24", &ArrayArray<int64_t, 32, 32>::append<boost::container::small_vector<int64_t, 24>>)
.def("push_back24", &ArrayArray<int64_t, 32, 32>::push_back<boost::container::small_vector<int64_t, 24>>)
.def("append_vector", &ArrayArray<int64_t, 32, 32>::append<std::vector<int64_t>>)
.def("push_back_vector", &ArrayArray<int64_t, 32, 32>::push_back<std::vector<int64_t>>)
.def("removeAt", &ArrayArray<int64_t, 32, 32>::removeAt)
.def("remove_at", &ArrayArray<int64_t, 32, 32>::remove_at)
.def("to_array", &ArrayArray<int64_t, 32, 32>::to_array)
.def("to_list", &ArrayArray<int64_t, 32, 32>::to_list)
.def("keys_len", &ArrayArray<int64_t, 32, 32>::keys_len)
.def("keys_size", &ArrayArray<int64_t, 32, 32>::keys_size)
.def("values_len", &ArrayArray<int64_t, 32, 32>::values_len)
.def("values_size", &ArrayArray<int64_t, 32, 32>::values_size)
//.def("get_size", &ArrayArray<int64_t, 32, 32>::size)
//.def("get_item", &ArrayArray<int64_t, 32, 32>::getItem)
.def("__len__", &ArrayArray<int64_t, 32, 32>::size)
.def("__getitem__", &ArrayArray<int64_t, 32, 32>::get<std::vector<int64_t>>);
